version: '3'

services: 
  oracle-db:
    build: ./database_environment/ 
    #image: oracleinanutshell/oracle-xe-11g:latest
    ports:
      - 1521:1521
      - 5500:5500
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_DISABLE_ASYNCH_IO=true
      - ORACLE_ENABLE_XDB=true
  python-app:
    build: ./application_environment/
    ports:
      - 8000:8000
      - 80:80
    environment:
      WAIT_HOSTS: oracle-db:1521
      WAIT_BEFORE_HOSTS: 90