version: '3'

services: 
  oracle-db:
    build: ./database_environment/ 
    #image: oracleinanutshell/oracle-xe-11g:latest
    ports:
      - 1521:1521
      - 5500:5500
      - 8080:8080
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_DISABLE_ASYNCH_IO=true
      - ORACLE_ENABLE_XDB=true
  #python-app:
  #  build: ./application_environment/
  #  ports:
  #    - 80:80