version: '3'

services:
    allegrograph-db:
        restart: always
        shm_size: 2g
        image: franzinc/agraph:v7.0.0
        environment:
          AGRAPH_SUPER_USER:  admin
          AGRAPH_SUPER_PASSWORD: pass
        ports:
          - 10000-10035:10000-10035
        volumes:
            - ./agdata:/agraph/data
            - ./agconfig:/agraph/etc
    python-app:
        container_name: app_allegro
        restart: always
        build: ./app/ 
        volumes:
            - ./app:/app
        ports:
            - 7000:7000
        environment:
            WAIT_HOSTS: allegrograph-db:10035
            WAIT_BEFORE_HOSTS: 30