version: "3.7"
services:
  mongodb_container:
    image: cockroach:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27077:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
